core/urls.py
"""
core URL Configuration
"""
from django.urls import path

from core.views import (AboutView, CartView, CheckoutView, HomeView,
                        MovieDetailView, WishlistView, add_to_cart,
                        add_to_wishlist, remove_from_cart,
                        remove_from_wishlist, ProfileView, HistoryView)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("cart/", CartView.as_view(), name="cart"),
    path("history/", HistoryView.as_view(), name="history"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("movie/<pk>/", MovieDetailView.as_view(), name="movie"),
    path("add-to-cart/<pk>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<pk>/", remove_from_cart, name="remove-from-cart"),
    path("add-to-wishlist/<pk>/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/<pk>/",
         remove_from_wishlist, name="remove-from-wishlist"),
    path("about/", AboutView.as_view(), name="about"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

movieflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls"), name="auth"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
"""
All models for core app are defined here.
"""
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django_countries.fields import CountryField


class Actor(models.Model):
    """
    Actor model.
    """
    name = models.CharField(max_length=100)  # Name of the actor

    class Meta:
        ordering = ["name"]  # Order actors by name

    def __str__(self):
        return self.name


class Director(models.Model):
    """
    Director model.
    """
    name = models.CharField(max_length=100)  # Name of the director

    class Meta:
        ordering = ["name"]  # Order directors by name

    def __str__(self):
        return self.name


class Genre(models.Model):
    """
    Genre model.
    """
    name = models.CharField(max_length=100)  # Name of the genre

    class Meta:
        ordering = ["name"]  # Order genres by name

    def __str__(self):
        return self.name


class Movie(models.Model):
    """
    Movie model.
    """

    title = models.CharField(max_length=100)  # Title of the movie
    runtime = models.IntegerField(blank=True, null=True)  # Movie runtime
    year = models.IntegerField()  # Release year of the movie
    description = models.TextField(null=True)  # Basic movie description

    # IMDb rating for the movie
    rating = models.DecimalField(decimal_places=1, max_digits=2)
    genre = models.ManyToManyField(Genre)  # Movie genres, foreign key to Genre

    # Movie director, foreign key to Director
    directors = models.ManyToManyField(Director)

    # Movie actors, foreign key to Actor
    actors = models.ManyToManyField(Actor)
    certificate = models.TextField(max_length=4)  # Age rating for the movie
    icon_url = models.SlugField(max_length=220, null=True)
    poster_url = models.SlugField(max_length=220, null=True)
    big_poster_url = models.SlugField(max_length=220, null=True)

    class Meta:
        ordering = ["runtime"]  # Order movies by runtime

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse("core:movie", kwargs={
            "pk": self.pk
        })

    def get_add_to_cart_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:add-to-cart", kwargs={
            "pk": self.pk
        })

    def get_remove_from_cart_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:remove-from-cart", kwargs={
            "pk": self.pk
        })

    def get_add_to_wishlist_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:add-to-wishlist", kwargs={
            "pk": self.pk
        })

    def get_remove_from_wishlist_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:remove-from-wishlist", kwargs={
            "pk": self.pk
        })

    def __str__(self):
        return self.title


class OrderItem(models.Model):
    """
    Links the Movie model. When a Movie object is added to the cart it becomes an OrderItem object.
    """
    # User who added the movie to the cart
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    item = models.ForeignKey(Movie, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)  # If the order is completed

    DURATION_CHOICES = [
        ("D", "One Day"),
        ("W", "One Week"),
        ("P", "Permanent"),
    ]
    duration = models.CharField(
        max_length=1,
        choices=DURATION_CHOICES,
        default="D"
    )

    price = models.DecimalField(  # Price of the movie
        max_digits=5,
        decimal_places=2,
        default=100.00,
    )

    def __str__(self):
        return f"{self.item.title} rented for {self.get_duration_display()}"

    def save(self, *args, **kwargs):
        """
        Overriding default save() function to set price dynamically.
        """
        if self.duration == "P":
            self.price = 300.00
        elif self.duration == "W":
            self.price = 200.00
        else:
            self.price = 100.00

        super().save(*args, **kwargs)


class Order(models.Model):
    """Stores all the movies in the cart. Can be thought of as the model for the User's cart."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # User who made the order

    items = models.ManyToManyField(OrderItem)  # Movies in the cart

    start_date = models.DateTimeField(
        auto_now_add=True
    )  # Date when the order was started

    ordered_date = models.DateTimeField()  # Date when the order was confirmed

    ordered = models.BooleanField(default=False)  # If the order is completed

    address = models.ForeignKey(
        "Address", on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.id}: {self.start_date}"

    def get_total(self):
        """
        Returns the total price of the order.
        """
        total = 0
        for order_item in self.items.all():
            total += order_item.price
        return total


class Address(models.Model):
    """The address model."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    pincode = models.CharField(max_length=100)
    default = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username


class WishlistItem(models.Model):
    """Add movies to wishlist"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    item = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.item.title}"


class Wishlist(models.Model):
    """Stores all movies in wishlist"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # User who added to the wishlist

    items = models.ManyToManyField(WishlistItem)  # Movies in the wishlist


class Profile(models.Model):
    """
    User profile model.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10, blank=True)
    profile_pic = models.ImageField(
        upload_to="profile_pics/", blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance=None, created=False, **kwargs):
    """
    Create a profile for the user when user is created.
    """
    if created:
        Profile.objects.create(user=instance)

core/forms.py
"""Forms"""
from django import forms
from django_countries.fields import CountryField


class Search(forms.Form):
    """Search form"""
    actor = forms.CharField(max_length=100, required=False)
    director = forms.CharField(max_length=100, required=False)
    genre = forms.CharField(max_length=60, required=False)


class ProfileForm(forms.Form):
    """Profile form"""
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    profile_pic = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=10, required=False)


class PasswordForm(forms.Form):
    """Password form"""
    password_old = forms.CharField(widget=forms.PasswordInput, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)


class CheckoutForm(forms.Form):
    """Checkout Form"""
    address1 = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "1234 Main St",
        "class": "form-control",
    }))
    address2 = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "placeholder": "Apartment or suite",
        "class": "form-control",
    }))
    country = CountryField().formfield(widget=forms.Select(attrs={
        "class": "form-select",
    }))
    pincode = forms.CharField(max_length=6, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "000000",
    }))
    set_default = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)
    PAYMENT_CHOICES = (
        ("C", "Credit Card"),
        ("D", "Debit Card"),
        ("U", "UPI"),
        ("COD", "Cash On Delivery"),
    )
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={
            "class": "custom-control-label",
        }), choices=PAYMENT_CHOICES)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Bootstrap v5.1.3-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block head %}{% endblock head %}
        <link rel="stylesheet" href="{% static "css/sticky_footer.css" %}">


        <!-- FontAwesome -->
        <script src="https://kit.fontawesome.com/6573a846cd.js" crossorigin="anonymous"></script>

    </head>

    <body class="bg-light">
        <div class="wrapper">
            <!-- Navbar -->
            {% include "partials/navbar.html" %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

            <!-- Body -->
            {% block body %}
            {% comment %} <div>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
                    {% endif %}
                </ul>
            </div> {% endcomment %}
            {% endblock body%}

            {% block content %}
            {% endblock content %}

            {% block extra_body %}
            {% endblock extra_body %}

            <!-- JS for Bootstrap v5.1.3 -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous">
            </script>

            <script>
                var elements = document.getElementsByClassName("btn-close");
                if (elements.length > 0) {
                    setTimeout(function () {
                        for (var i = 0; i < elements.length; i++) {
                            elements[i].click();
                        }
                    }, 3000)
                }
            </script>

            {% block scripts %}
            {% endblock scripts %}
        </div>
        {% include "partials/footer.html" %}
    </body>

</html>

core/templates/cart.html
{% extends "base.html" %}

{% block head %}
<title>Movieflix | Cart</title>
{% endblock head %}

{% block content %}
<div class="container">
    <div class="table-responsive text-nowrap">
        <h2 class="mt-3">Order Summary</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="text-center">#</th>
                    <th scope="col" class="text-center">Movie Name</th>
                    <th scope="col" class="text-center">Rental Duration</th>
                    <th scope="col" class="text-center">Remove</th>
                    <th scope="col" class="text-center">Price</th>
                </tr>
            </thead>
            <tbody>
                {% if order.items.all %}
                {% for order_item in order.items.all %}
                <tr>
                    <th scope="row" class="text-center">{{ forloop.counter }}</th>
                    <td class="text-center"> <a class="text-decoration-none text-dark"
                            href="{{ order_item.item.get_absolute_url }}">
                            {{ order_item.item.title }}</a></td>
                    <td class="text-center">{{ order_item.get_duration_display }}</td>
                    <td class="text-center"><a href="{{order_item.item.get_remove_from_cart_url}}"
                            class="btn btn-danger btn-md-my-0 p">
                            <span class="fas fa-trash-alt"></span>
                        </a></td>
                    <td class="text-center">&#x20B9;{{ order_item.price }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4">Order Total:</th>
                    <td class="text-center"><b>&#x20B9;{{order.get_total}}</b></td>
                </tr>
                <tr>
                    <td colspan="5" class="text-center"><a href="/checkout" class="btn btn-warning">
                            Checkout
                        </a></td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="5" class="text-center"><a href="/" class="btn btn-success">
                            Your cart is empty :( Shop more!
                        </a></td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

core/templates/checkout.html
{% extends "base.html" %}
{% load i18n static %}


{% block head %}
<title>Movieflix | Checkout</title>
<style>
    .container {
        max-width: 960px;
    }
</style>
{% endblock head %}

{% block content %}
<div class="py-5 text-center">
    <h2>Checkout</h2>
</div>
<div class="container">

    <div class="row g-5">
        <div class="col-md-5 col-lg-4 order-md-last card card-body bg-dark">
            <h4 class="d-flex justify-content-between align-items-center mb-3 card-header text-white">
                <span class="">Your cart</span>
                <span class="badge bg-white rounded-pill text-dark">{{order.items.count}}</span>
            </h4>
            <ul class="list-group mb-3">
                {% for item in order.items.all %}
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">{{item.item.title}}</h6>
                        {% if item.duration == "P" %}
                        <small class="text-muted">Buying {{item.get_duration_display|lower}}ly</small>
                        {% else %}
                        <small class="text-muted">Buying for {{item.get_duration_display|lower}}</small>
                        {% endif %}
                    </div>
                    <span class="text-muted">&#x20B9;{{item.price}}</span>
                </li>
                {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total</span>
                    <strong>&#x20B9;{{order.get_total}}</strong>
                </li>
            </ul>
            <a class="btn btn-light" href="{% url "core:cart" %}">Edit Order</a>
        </div>
        <div class="col-md-7 col-lg-8 card card-body bg-light">
            <form method="POST" class="needs-validation" novalidate>
                <h4 class="mb-3"> Address</h4>
                {% csrf_token %}
                <div class="row g-3">
                    <div class=" col-12">
                        <label for="address1" class="form-label">Address 1</label>
                        {{form.address1}}
                        <div class="invalid-feedback">
                            Please enter your address.
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="address2" class="form-label">Address 2 <span
                                class="text-muted">(Optional)</span></label>
                        {{form.address2}}
                    </div>

                    <div class="col-md-5">
                        <label for="country" class="form-label">Country</label>
                        {{ form.country }}
                        <div class="invalid-feedback">
                            Please select a valid country.
                        </div>
                    </div>

                    <div class="col-md-3">
                        <label for="pincode" class="form-label">Pincode</label>
                        {{ form.pincode }}
                        <div class="invalid-feedback">
                            Pincode required.
                        </div>
                    </div>
                </div>
                <div class="form-check mt-2">
                    <input name="set_default" {% if form.set_default.value %}checked{% endif %} type="checkbox"
                        class="form-check-input">
                    <label class="form-check-label" for="set_default">Save as default address for next
                        time</label>
                </div>

                {% if default_address %}
                <div class="form-check">
                    <input id="use_default" name="use_default" {% if form.use_default.value %}checked{% endif %}
                        type="checkbox" class="form-check-input">
                    <label class="form-check-label" for="use_default">Use default
                        address: <span class="text-muted">{{default_address.address1|truncatechars:10}}</span></label>
                </div>
                <script>
                    document.getElementById("use_default").addEventListener("change", function () {
                        if (this.checked) {
                            console.log("checked");
                            document.getElementById("id_address1").value = "{{default_address.address1}}";
                            document.getElementById("id_address2").value = "{{default_address.address2}}";
                            document.getElementById("id_country").value = "{{default_address.country}}";
                            document.getElementById("id_pincode").value = "{{default_address.pincode}}";
                        } else {
                            console.log("unchecked");
                            document.getElementById("id_address1").value = "";
                            document.getElementById("id_address2").value = "";
                            document.getElementById("id_country").value = "";
                            document.getElementById("id_pincode").value = "";
                        }
                    });
                </script>
                {% endif %}
                <hr class="my-4">

                <h4 class="mb-3">Payment</h4>

                <div class="my-3">
                    {% for value, name in form.fields.payment_option.choices %}
                    <div class="form-check">
                        <input id="{{ name }}" value="{{ value }}" name="payment_option" type="radio"
                            class="form-check-input" required>
                        <label class="form-check-label" for="{{ name }}">{{ name }}</label>
                    </div>
                    {% endfor %}
                </div>

                <hr class="my-4">

                <button class="w-100 btn btn-secondary btn-lg" type="submit">Complete Order</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

core/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<title>Movieflix | Profile</title>
<link rel="stylesheet" href="{% static "css/profile.css" %}">
{% endblock head %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
                <div class="col-md-4 border-right">
                        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                                <img class="rounded-circle mt-5" width="150px"
                                        src="{% if profile.profile_pic %}{{profile.profile_pic.url}}{% else %}https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg{% endif %}"><span
                                        class="font-weight-bold">
                                        {% if user.get_full_name %}
                                        {{user.get_full_name}}
                                        {% else %}
                                        {{user.username}}
                                        {% endif %}
                                </span>
                                <span class="text-black-50">{% if user.email %}{{user.email}}{% else %}Add your
                                        email{% endif %}</span><span>
                                </span><span class="mt-5"><a href="/history"
                                                class="btn btn-dark text-decoration-none">View
                                                your past
                                                orders</a></span></div>
                </div>
                <div class="col-md-6 border-right">
                        <div class="p-3 py-5">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                        <h4 class="text-right">Profile Details</h4>
                                </div>
                                <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row mt-2">
                                                <div class="col-md-6"><label class="labels">Name</label><input
                                                                type="text" name="first_name" id="id_first_name"
                                                                class="form-control"
                                                                {% if user.first_name %}value="{{user.first_name}}"
                                                                {% else %} placeholder="Add first name" {% endif %}>
                                                </div>
                                                <div class="col-md-6"><label class="labels">Surname</label><input
                                                                type="text" name="last_name" id="id_last_name"
                                                                class="form-control"
                                                                {% if user.last_name %}value="{{user.last_name}}"
                                                                {% else %} placeholder="Add last name" {% endif %}>
                                                </div>
                                        </div>
                                        <div class="row mt-3">
                                                <div class="col-md-12"><label class="labels">Username</label><input
                                                                type="text" name="username" id="id_username"
                                                                class="form-control"
                                                                {% if user.username %}value="{{user.username}}"
                                                                {% else %} placeholder="Add username" {% endif %}></div>
                                                <div class="col-md-12"><label class="labels">Phone Number</label><input
                                                                type="text" name="phone_number" id="id_phone_number"
                                                                class="form-control"
                                                                {% if profile.phone_number %}value="{{profile.phone_number}}"
                                                                {% else %} placeholder="Enter phone number" {% endif %}>
                                                </div>
                                                <div class="col-md-12"><label class="labels">Email
                                                                ID</label><input type="text" name="email" id="id_email"
                                                                class="form-control" {% if user.email %}
                                                                value="{{user.email}}" {% else %}
                                                                placeholder="Enter email ID" {% endif %}>
                                                </div>
                                                <div class="col-md-12"><label class="labels">Profile
                                                                Picture</label><input type="file" name="profile_pic"
                                                                id="id_profile_pic" class="form-control"
                                                                accept="image/*">
                                                </div>
                                                <hr class="mt-3">
                                                <h5 class="mb-4">Change Password</h5>
                                                <div class="col-md-12"><label class="labels">Old Password</label><input
                                                                type="password" name="password_old" id="id_password_old"
                                                                class="form-control" placeholder="Enter old password">
                                                </div>
                                                <div class="col-md-12"><label class="labels">New Password</label><input
                                                                type="password" name="password1" id="id_password1"
                                                                class="form-control" placeholder="Enter new password">
                                                </div>
                                                <div class="col-md-12"><label class="labels">Confirm New
                                                                Password</label><input type="password" name="password2"
                                                                id="id_password2" class="form-control"
                                                                placeholder="Confirm new password">
                                                </div>
                                                <div class="mt-5 text-center"><button
                                                                class="btn btn-primary profile-button"
                                                                type="submit">Save
                                                                Profile</button></div>
                                </form>
                        </div>
                </div>
        </div>
</div>

{% endblock content %}

core/templates/wishlist.html
{% extends "base.html" %}

{% block head %}
<title>Movieflix | Wishlist</title>
{% endblock head %}

{% block content %}
<div class="container">
    <div class="table-responsive">
        <h2 class="mt-3">Your Wishlist</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" class="col-1 text-center">#</th>
                    <th scope="col" class="col-3 text-center">Movie Name</th>
                    <th scope="col" class="col-5 text-center">Summary</th>
                    <th scope="col" class="col-2 text-center">IMDb Rating</th>
                    <th scope="col" class="col-1 text-center">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% if wishlist.items.all %}
                {% for wishlist_item in wishlist.items.all %}
                <tr>
                    <th scope="row" class="col-1 text-center">{{ forloop.counter }}</th>
                    <td class="col-3 text-center"> <a class="text-decoration-none text-dark"
                            href="{{ wishlist_item.item.get_absolute_url }}">
                            {{ wishlist_item.item.title }}</a></td>
                    <td class="col-5 text-justify">{{ wishlist_item.item.description }}</td>
                    <td class="col-2 text-center">{{ wishlist_item.item.rating }}</td>
                    <td class="col-1 text-center"><a href="{{wishlist_item.item.get_remove_from_wishlist_url}}"
                            class="btn btn-danger btn-md-my-0 p">
                            <span class="fas fa-trash-alt"></span>
                        </a></td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="6" class="col-6 text-center"><a href="/" class="btn btn-success">
                            Your Wishlist is empty :( Add some exciting movies!
                        </a></td>
                </tr>

                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}