core/urls.py
"""
core URL Configuration
"""
from django.urls import path

from core.views import (AboutView, CartView, CheckoutView, HomeView,
                        MovieDetailView, WishlistView, add_to_cart,
                        add_to_wishlist, remove_from_cart,
                        remove_from_wishlist, ProfileView, HistoryView)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("cart/", CartView.as_view(), name="cart"),
    path("history/", HistoryView.as_view(), name="history"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("movie/<pk>/", MovieDetailView.as_view(), name="movie"),
    path("add-to-cart/<pk>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<pk>/", remove_from_cart, name="remove-from-cart"),
    path("add-to-wishlist/<pk>/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/<pk>/",
         remove_from_wishlist, name="remove-from-wishlist"),
    path("about/", AboutView.as_view(), name="about"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

movieflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls"), name="auth"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
"""
All models for core app are defined here.
"""
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django_countries.fields import CountryField


class Actor(models.Model):
    """
    Actor model.
    """
    name = models.CharField(max_length=100)  # Name of the actor

    class Meta:
        ordering = ["name"]  # Order actors by name

    def __str__(self):
        return self.name


class Director(models.Model):
    """
    Director model.
    """
    name = models.CharField(max_length=100)  # Name of the director

    class Meta:
        ordering = ["name"]  # Order directors by name

    def __str__(self):
        return self.name


class Genre(models.Model):
    """
    Genre model.
    """
    name = models.CharField(max_length=100)  # Name of the genre

    class Meta:
        ordering = ["name"]  # Order genres by name

    def __str__(self):
        return self.name


class Movie(models.Model):
    """
    Movie model.
    """

    title = models.CharField(max_length=100)  # Title of the movie
    runtime = models.IntegerField(blank=True, null=True)  # Movie runtime
    year = models.IntegerField()  # Release year of the movie
    description = models.TextField(null=True)  # Basic movie description

    # IMDb rating for the movie
    rating = models.DecimalField(decimal_places=1, max_digits=2)
    genre = models.ManyToManyField(Genre)  # Movie genres, foreign key to Genre

    # Movie director, foreign key to Director
    directors = models.ManyToManyField(Director)

    # Movie actors, foreign key to Actor
    actors = models.ManyToManyField(Actor)
    certificate = models.TextField(max_length=4)  # Age rating for the movie
    icon_url = models.SlugField(max_length=220, null=True)
    poster_url = models.SlugField(max_length=220, null=True)
    big_poster_url = models.SlugField(max_length=220, null=True)

    class Meta:
        ordering = ["runtime"]  # Order movies by runtime

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse("core:movie", kwargs={
            "pk": self.pk
        })

    def get_add_to_cart_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:add-to-cart", kwargs={
            "pk": self.pk
        })

    def get_remove_from_cart_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:remove-from-cart", kwargs={
            "pk": self.pk
        })

    def get_add_to_wishlist_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:add-to-wishlist", kwargs={
            "pk": self.pk
        })

    def get_remove_from_wishlist_url(self):
        """
        Returns the url to add the movie to cart.
        """
        return reverse("core:remove-from-wishlist", kwargs={
            "pk": self.pk
        })

    def __str__(self):
        return self.title


class OrderItem(models.Model):
    """
    Links the Movie model. When a Movie object is added to the cart it becomes an OrderItem object.
    """
    # User who added the movie to the cart
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    item = models.ForeignKey(Movie, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)  # If the order is completed

    DURATION_CHOICES = [
        ("D", "One Day"),
        ("W", "One Week"),
        ("P", "Permanent"),
    ]
    duration = models.CharField(
        max_length=1,
        choices=DURATION_CHOICES,
        default="D"
    )

    price = models.DecimalField(  # Price of the movie
        max_digits=5,
        decimal_places=2,
        default=100.00,
    )

    def __str__(self):
        return f"{self.item.title} rented for {self.get_duration_display()}"

    def save(self, *args, **kwargs):
        """
        Overriding default save() function to set price dynamically.
        """
        if self.duration == "P":
            self.price = 300.00
        elif self.duration == "W":
            self.price = 200.00
        else:
            self.price = 100.00

        super().save(*args, **kwargs)


class Order(models.Model):
    """Stores all the movies in the cart. Can be thought of as the model for the User's cart."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # User who made the order

    items = models.ManyToManyField(OrderItem)  # Movies in the cart

    start_date = models.DateTimeField(
        auto_now_add=True
    )  # Date when the order was started

    ordered_date = models.DateTimeField()  # Date when the order was confirmed

    ordered = models.BooleanField(default=False)  # If the order is completed

    address = models.ForeignKey(
        "Address", on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.id}: {self.start_date}"

    def get_total(self):
        """
        Returns the total price of the order.
        """
        total = 0
        for order_item in self.items.all():
            total += order_item.price
        return total


class Address(models.Model):
    """The address model."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    pincode = models.CharField(max_length=100)
    default = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username


class WishlistItem(models.Model):
    """Add movies to wishlist"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    item = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.item.title}"


class Wishlist(models.Model):
    """Stores all movies in wishlist"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # User who added to the wishlist

    items = models.ManyToManyField(WishlistItem)  # Movies in the wishlist


class Profile(models.Model):
    """
    User profile model.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10, blank=True)
    profile_pic = models.ImageField(
        upload_to="profile_pics/", blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance=None, created=False, **kwargs):
    """
    Create a profile for the user when user is created.
    """
    if created:
        Profile.objects.create(user=instance)

core/forms.py
"""Forms"""
from django import forms
from django_countries.fields import CountryField


class Search(forms.Form):
    """Search form"""
    actor = forms.CharField(max_length=100, required=False)
    director = forms.CharField(max_length=100, required=False)
    genre = forms.CharField(max_length=60, required=False)


class ProfileForm(forms.Form):
    """Profile form"""
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    profile_pic = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=10, required=False)


class PasswordForm(forms.Form):
    """Password form"""
    password_old = forms.CharField(widget=forms.PasswordInput, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)


class CheckoutForm(forms.Form):
    """Checkout Form"""
    address1 = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "1234 Main St",
        "class": "form-control",
    }))
    address2 = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "placeholder": "Apartment or suite",
        "class": "form-control",
    }))
    country = CountryField().formfield(widget=forms.Select(attrs={
        "class": "form-select",
    }))
    pincode = forms.CharField(max_length=6, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "000000",
    }))
    set_default = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)
    PAYMENT_CHOICES = (
        ("C", "Credit Card"),
        ("D", "Debit Card"),
        ("U", "UPI"),
        ("COD", "Cash On Delivery"),
    )
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={
            "class": "custom-control-label",
        }), choices=PAYMENT_CHOICES)

core/templates/partials/footer.html
<footer class="footer mt-auto bg-light text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3 text-light" style="background-color: rgb(33, 37, 41);">
        &copy; 2021 Copyright Movieflix. All rights reserved.
        <br>
        Ashoka University, NH 44, Rajiv Gandhi Education City, Sonipat,
        Haryana-131029
    </div>
</footer>

core/templates/partials/navbar.html
{% load tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "core:home" %}">Movieflix</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "core:about" %}">About</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated %}
                        Welcome {{ user.username }}

                        {% else %}
                        Welcome Guest
                        {% endif %}
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url "core:profile" %}">
                            Profile
                            <span class="fas fa-user"></span>
                        </a>
                        <a class="dropdown-item" href="{% url "core:cart" %}">
                            {% if request.user|cart_item_count == 0 %}
                            Cart
                            <span class="fas fa-shopping-cart"></span>
                            {% elif request.user|cart_item_count == 1 %}
                            <span class="z-depth mr-1">{{ request.user|cart_item_count }} item in Cart</span>
                            {% else %}
                            <span class="z-depth mr-1">{{ request.user|cart_item_count }} items in Cart</span>
                            {% endif %}
                        </a>
                        <a class="dropdown-item" href="{% url "core:wishlist" %}">
                            {% if request.user|wishlist_item_count == 0 %}
                            Wishlist
                            <span class="fas fa-heart ml-1"></span>
                            {% elif request.user|wishlist_item_count == 1 %}
                            <span class="z-depth mr-1">{{ request.user|wishlist_item_count }} item
                                in Wishlist</span>
                            {% else %}
                            <span class="z-depth mr-1">{{ request.user|wishlist_item_count }} items
                                in Wishlist</span>
                            {% endif %}
                        </a>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <form action="{% url "account_logout" %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="dropdown-item btn btn-link" value="Sign Out">
                        </form>

                        {% else %}
                        <a class="dropdown-item" href="{% url "account_login" %}">Sign In</a>
                        <a class="dropdown-item" href="{% url "account_signup" %}">Sign Up</a>
                        {% endif %}
                    </ul>
                </li>
            </ul>

            <form action="{% url "core:home" %}" method="GET" class="d-flex flex-row-reverse">
                <button class="btn btn-outline-success" type="submit"><span class="fas fa-search"></span></button>
                <input class="form-control me-2 w-25" type="search" placeholder="Search by actor" name="actor"
                    aria-label="Search by actor" maxlength="100" id="id_actor">
                <input class="form-control me-2 w-25" type="search" placeholder="Search by director" name="director"
                    aria-label="Search by director" maxlength="100" id="id_director">
                <input class="form-control me-2 w-25" type="search" placeholder="Search by genre" name="genre"
                    aria-label="Search by genre" maxlength="60" id="id_genre">
            </form>
        </div>
    </div>
</nav>